Fix #81, #83: Explain how to uses toolchain files and define missing Windows Exports
rticommunity/rticonnextdds-cmake-utils pull request #82
Opened 2023-02-10 14:44 UTC by lulivi

Fixes #81
Fixes #83 

### Proposed changes

### Comments

### Logs

<details>
  <summary>Before the fix</summary>
  <pre>
Done Building Project "C:\Users\testadmin\rticonnextdds-examples\examples\cloud_discovery_service\library_api\c\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\testadmin\rticonnextdds-examples\examples\cloud_discovery_service\library_api\c\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\testadmin\rticonnextdds-examples\examples\cloud_discovery_service\library_api\c\build\CloudDiscoveryServiceLibraryAPIC.vcxproj" (default target) (3) ->
(Link target) ->
  cloud_discovery_service_library_api.obj : error LNK2019: unresolved external symbol RTI_CDS_LOG_VERBOSITY_ALL referenced in function main [C:\Users\testadmin\rticonnextdds-examples\examples\cloud_discovery_service\library_api\c\build\CloudDiscoveryServiceLibraryAPIC.vcxproj]
  cloud_discovery_service_library_api.obj : error LNK2019: unresolved external symbol RTI_CDS_LOG_VERBOSITY_EXCEPTIONS referenced in function main [C:\Users\testadmin\rticonnextdds-examples\examples\cloud_discovery_service\library_api\c\build\CloudDiscoveryServiceLibraryAPIC.vcxproj]
  C:\Users\testadmin\rticonnextdds-examples\examples\cloud_discovery_service\library_api\c\build\Release\CloudDiscoveryServiceLibraryAPIC.exe : fatal error LNK1120: 2 unresolved externals [C:\Users\testadmin\rticonnextdds-examples\examples\cloud_discovery_service\library_api\c\build\CloudDiscoveryServiceLibraryAPIC.vcxproj]

    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:01.82
  </pre>
</details>

<details>
  <summary>After the fix</summary>
  <pre>
Done Building Project "C:\Users\testadmin\rticonnextdds-examples\examples\cloud_discovery_service\library_api\c\build\ALL_BUILD.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.24
  </pre>
</details>

2023-02-12 01:03 UTC, fgaranda approved these changes

2023-02-12 01:17 UTC, fgaranda approved these changes

2023-02-13 05:06 UTC, rkorte commented on cmake/Modules/FindRTIConnextDDS.cmake
> +# ^^^^^^^^^^^^^^^^^^
Is this really a subsection of "Supported platforms"?

2023-02-13 05:08 UTC, rkorte commented on cmake/Modules/FindRTIConnextDDS.cmake
>  # Some flags related to the compiler, like (-std=c++11 needed when linking
I think you mean this:

Some flags related to the compiler, (such as -std=c++11, needed when linking

2023-02-13 05:09 UTC, rkorte commented on cmake/Modules/FindRTIConnextDDS.cmake
>  # For versions lower than CMake 3.15, ``CONNEXTDDS_LOG_LEVEL`` variable should
insert the word "the" before ``CONNEXTDDS_LOG_LEVEL``

2023-02-13 05:10 UTC, rkorte commented on cmake/Modules/FindRTIConnextDDS.cmake
>  # Connext DDS:
Just say RTI Connext (no DDS)

(don't bother searching and replacing all ... we should update this as we can, and be consistent within a file ... if changing all instances in a file is too big a job, then leave it alone)

2023-02-13 05:11 UTC, rkorte requested changes
comments indicated

2023-02-16 12:56 UTC, fgaranda submitted a review, later dismissed

2023-02-16 17:27 UTC, rkorte approved these changes

2023-02-16 18:43 UTC, merged